import { useEffect } from 'react';
import { useQueryClient } from '@tanstack/react-query';

import { WebSocketClient } from '@/api/websocket';
import { keys } from '@/api/queryKeys';
import { isRecentLocalInvalidate } from '@/api/invalidationTracker';

type Handler = (payload: unknown) => void;
type InvalidateType = 'inbounds' | 'clients' | 'presence';

interface SharedClient {
  connect(): void;
  on(event: string, fn: Handler): void;
  off(event: string, fn: Handler): void;
}

let sharedClient: SharedClient | null = null;

function getSharedClient(): SharedClient {
  if (sharedClient) return sharedClient;
  const basePath = (typeof window !== 'undefined' && window.X_UI_BASE_PATH) || '';
  sharedClient = new WebSocketClient(basePath) as SharedClient;
  return sharedClient;
}

const invalidateTimers = new Map<InvalidateType, number>();

export function websocketInvalidateQueryKey(
  type: unknown,
): readonly unknown[] | null {
  if (type === 'inbounds') return keys.inbounds.root();
  if (type === 'clients') return keys.clients.root();
  if (type === 'presence') return keys.clients.onlines();
  return null;
}

export function useWebSocketBridge() {
  const queryClient = useQueryClient();

  useEffect(() => {
    const client = getSharedClient();

    const onInvalidate: Handler = (payload) => {
      const rawType = (payload as { type?: unknown } | undefined)?.type;
      const queryKey = websocketInvalidateQueryKey(rawType);
      if (!queryKey) return;

      const type = rawType as InvalidateType;
      const previous = invalidateTimers.get(type);
      if (previous != null) window.clearTimeout(previous);

      const timer = window.setTimeout(() => {
        invalidateTimers.delete(type);
        // Presence is generated by the server's oversize-payload fallback, not
        // by a local CRUD mutation, so it must never be suppressed here.
        if (type !== 'presence' && isRecentLocalInvalidate()) return;
        queryClient.invalidateQueries({ queryKey });
      }, 200);
      invalidateTimers.set(type, timer);
    };

    const onOutbounds: Handler = (payload) => {
      queryClient.setQueryData(keys.xray.outboundsTraffic(), payload);
    };

    const onNodes: Handler = (payload) => {
      if (!Array.isArray(payload)) return;
      queryClient.setQueryData(keys.nodes.list(), payload);
    };

    const onInbounds: Handler = (payload) => {
      if (!Array.isArray(payload)) return;
      queryClient.setQueryData(keys.inbounds.slim(), payload);
    };

    client.on('invalidate', onInvalidate);
    client.on('outbounds', onOutbounds);
    client.on('nodes', onNodes);
    client.on('inbounds', onInbounds);
    client.connect();

    return () => {
      client.off('invalidate', onInvalidate);
      client.off('outbounds', onOutbounds);
      client.off('nodes', onNodes);
      client.off('inbounds', onInbounds);
      for (const timer of invalidateTimers.values()) {
        window.clearTimeout(timer);
      }
      invalidateTimers.clear();
    };
  }, [queryClient]);
}
